spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keepnote?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089
