version: '3'
services:

  user-mysql:
     image: mysql:5.7
     network_mode: host
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_PASSWORD: root
       MYSQL_DATABASE: keepnote
       MYSQL_HOST: localhost
  user-mongo:
     image: mongo
     network_mode: host
     ports:
       - "27017:27017"
     environment:
       MONGO_DATABASE: keepnote
       MONGO_PORT: 27017
       MONGO_HOST: localhost
       
  category-service:
     image: category-service
     build: 
       context: CategoryService/
     depends_on:
       - user-mongo
     ports:
       - "8083:8083"
     network_mode: host
     restart: always
     
  noteservice:
     image: note-service
     build: 
       context: NoteService/
     depends_on:
       - user-mongo
     ports:
       - "8082:8082"
     network_mode: host
     restart: always
     
  reminderservice:
     image: reminder-service
     build: 
       context: ReminderService/
     depends_on:
       - user-mongo
     ports:
       - "8081:8081"
     network_mode: host
     restart: always
     
  userauthentication-Service:
     image: userauthentication-service
     build: 
       context: UserAuthentication-Service/
     depends_on:
       - user-mysql
     ports:
       - "8089:8089"
     network_mode: host
     restart: always
     
  userservice:
     image: user-service
     build: 
       context: UserService/
     depends_on:
       - user-mongo
     ports:
       - "8080:8080"
     network_mode: host
     restart: always 